spring:
  application:
    name: gcpcourt
  cloud:
    gcp:
      project-id: practicecourtstorage
      credentials:
        location: classpath:/secret/key-storage.json
      sql:
        instance-connection-name: practicecourtstorage:europe-north1:courtusers
        database-name: user

  datasource:
    username: admin
    password: admin

bucket-name: gcpcourt
