spring:
  application:
    name: gcpcourt
  cloud:
    gcp:
      project-id: ${GCP_PROJECT}
      credentials:
        encoded-key: ${GCP_CREDENTIALS}
      sql:
        instance-connection-name: ${GCP_SQL_INSTANCE_CONNECTION_NAME}
        database-name: ${GCP_SQL_DATABASE}

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${GCP_SQL_USERNAME}
    password: ${GCP_SQL_PASSWORD}

bucket-name: ${GCP_STORAGE_BUCKET}
