spring:
  application:
    name: gcpcourt
  cloud:
    gcp:
      project-id: practicecourtstorage
      credentials:
        encoded-key: ${GCP_CREDENTIALS}
      sql:
        instance-connection-name: practicecourtstorage:europe-north1:courtusers
        database-name: user

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${GCP_SQL_USERNAME}
    password: ${GCP_SQL_PASSWORD}

bucket-name: ${GCP_STORAGE_BUCKET}
