spring:
  application:
    name: gcpcourt
  cloud:
    gcp:
      project-id: practicecourtstorage
      credentials:
        location: classpath:/secret/key-storage.json
      sql:
        instance-connection-name: practicecourtstorage:europe-north1:courtusers
        database-name: user

  jpa:
    show-sql: true
#    hibernate:
#      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: admin


bucket-name: gcpcourt
